# Blog info
blog_name: Vnnyu
slogan: 幸甚至哉，歌以咏志。
url: http://www.vnnyu.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.png

# Set favicon
favicon: /images/avatar.png

# For seo
keywords: vnnyu,前端,前端开发,frontend,nodejs,JavaScript

home_nav:
  - name: 文章
    url: /archives
    target_blank: false #不在新页面打开
  #- name: 项目
  #  url: /project/
  #  target_blank: true #在新页面打开
  - name: 关于
    url: /about/
    target_blank: true
  #- name: Github
  #  url: https://github.com/Vnnyu
  #  target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  # - name: 友链
  #   url: /link/
  #   target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  # - name: RSS
  #   url: /atom.xml
  #   target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: ROUND_RECT  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 导航

search_slogan:
  isShow: true # true|fase
  text: 请搜索 ~

# link_slogan:
#   isShow: false # true|fase
#   text: 交换友链可以邮件 forsigner@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 联系或捐赠
  tip: 联系我或者捐赠我
  items:
    - type: 微信
      imgUrl: /images/qr-wechat-2.png
    - type: 微信
      imgUrl: /images/qr-wechat-1.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: false
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: dark # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
# google_analytics:
# baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service

# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: false # 如果使用 gitalk，请设置改之为true
  clientID: 277317290454635afa73
  clientSecret: 78223c859304da5e8d71bfce136d436c6ff95c37
  repo: blog-comment
  owner: forsigner
  admin: forsigner


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "李东浩，1994."
    - "前端工程师"
  - type: education
    icon: icon-text
    text_value: 
    - "北京交通大学，硕士，2018"
    - "贝壳找房，2017.8至今（实习&正式）"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@Vnnyu"
    text_value_url: https://github.com/Vnnyu
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "ldh71777@gmail.com"
  - type: location
    icon: icon-location
    text_value: 北京
  - type: wechat
    icon: icon-wechat
    text_value: "ldh_cain"
# link:
#   - name: 织网
#     info: 身体和灵魂，总有一个在路上
#     url: http://zheng-ji.info/
#     avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
#   - name: Dongyado
#     info: 生命不止，折腾不息
#     url: http://dongyado.com/
#     avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
#   - name: OrangeCoder
#     info: android ffmpeg nodejs gradle
#     url: http://orangecoder.com/
#     avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
#   - name: EverET
#     info: 好记性不如烂笔头
#     url: http://everet.org/about-me/
#     avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
#   - name: 题叶
#     info: FP, GUI, Writing
#     url: http://tiye.me/
#     avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
#   - name: McChen
#     info: Stay Hungry, Stay Foolish
#     url: http://mcchen.club/
#     avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
